version: '3.8'
services:
  frontend:
    build: ./FrontendService
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./BackendService
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    volumes:
      - ./BackendService:/usr/src/app
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_NAME=mydatabase

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
